spring.datasource.url=jdbc:postgresql://localhost:5432/social_network_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Chỉ kiểm tra xem Code Entity có khớp với Bảng SQL không (Không tự tạo/sửa bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=DayLaCaiKeySieuBiMatCuaHienTranCoding2026PhaiDaiHon32KyTuMoiDuoc
app.jwt.expiration=86400000
# Cloudinary Config
cloudinary.cloud-name=ddtzulrbl
cloudinary.api-key=735819923968436
cloudinary.api-secret=y0D885n8XUbkot_JZ06efDKQOBc