# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/TEN_DATABASE_CUA_BAN
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security JWT
app.jwt.secret=
app.jwt.expiration=86400000

# Cloudinary - Copy tu Notepad vao day nhe
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=